### ISSUE TITLE
No value - Just some after reboot HA

### ISSUE THREAD

**Issue by KaRLiKCZ** [denpamusic/homeassistant-plum-ecomax#115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I'm having the following issue:

Hi Denis,

I have a problem with Plum EcoMAX already couple months. It starter later on spring, but I knew I will stop my boiler in couple weeks so I decided to wait if some future update solve the issue. But problem still persist.
I didn't change any HW in year or more so I hope HW is OK. I tried to switch all the HW off for some minutes and started everything, but no change. I tried to completely remove PLUM, restart HA and also OS and install after that freshly. No change. I'm able to connect with ecoMAX 800 R3. I see main, mixer, thermostat.
When I add it I get new values. Temperatures mainly now, as boiler is OFF. But then updating temperatures stop.
Sometimes I get values for couple minutes, sometime just one value (for each entity).

### I have following devices connected:

- [ ] ecoMAX 3xx series
- [X] ecoMAX 8xx series
- [ ] ecoMAX 9xx series
- [ ] Expansion module B
- [ ] Expansion module C
- [ ] ecoSTER 200/ecoSTER Touch
- [ ] ecoLAMBDA
- [ ] ecoNET 300

### I'm connecting to my devices using:

Ethernet/WiFi to RS-485 converter

### I'm seeing following log messages:

```shell
2024-07-31 13:20:55.288 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry ecoMAXX 800R3 for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 801, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 237, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

### My diagnostics data:

[config_entry-plum_ecomax-01J3V2D9EM9BAJNJ3Y24MQPQEF (1).json](https://github.com/user-attachments/files/16440530/config_entry-plum_ecomax-01J3V2D9EM9BAJNJ3Y24MQPQEF.1.json)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by denpamusic** [comment]
Hi,

Thank you for the feedback.

Firstly, just in case, temperatures fluctuations of less then [0.1°C](https://github.com/denpamusic/PyPlumIO/blob/be5362e5d0e616841b66e7ad4ff9fae83fec12f9/pyplumio/filters.py#L24) are ignored to save space in HA db. As boiler is off, temperatures probably staying relatively the same, hence it may seem like it's not updating. For example if your feed water temp is 19.7°C it won't update if it's changed to 19.75°C, it will only update once it reaches 19.8°C or falls down to 19.6°C.

I can see, that you have outside temperature sensor, please check if it is updated and stays true to your outdoor temperature. If outdoor temperature not updating, we'll debug this issue further.

**Comment by KaRLiKCZ** [comment]
Hi, 
That is the value I'm checking right now. Outside temperature as it change a lot :)
An also temperature of hot water as it is on electric heater and I can measure it and see also temperature on thermostat.

That is also maybe important. I see outside temperature and hot water temperature on thermostat in my living room.

Ondrej

**Comment by denpamusic** [comment]
Ok, then. It's most definitely shouldn't be `Unavailable`. When you downloaded diagnostics data, that you attached to this issue, was your outside temperature listed as `Unavailable` in HA?

**Comment by KaRLiKCZ** [comment]
I just downloaded again. First when it was not available and send after restart (not immediately, but still entities shown like available)
[config_entry-plum_ecomax-01J3V2D9EM9BAJNJ3Y24MQPQEF_available.json](https://github.com/user-attachments/files/16442239/config_entry-plum_ecomax-01J3V2D9EM9BAJNJ3Y24MQPQEF_available.json)
[config_entry-plum_ecomax-01J3V2D9EM9BAJNJ3Y24MQPQEF_not_available.json](https://github.com/user-attachments/files/16442240/config_entry-plum_ecomax-01J3V2D9EM9BAJNJ3Y24MQPQEF_not_available.json)

**Comment by denpamusic** [comment]
Very strange, since I see `outside_temp` field being present in both diagnostics data.

Could you, please, downgrade to plum-ecomax v0.4.3. Since v0.4.4 is released on May, 4th this roughly corresponds with the time the issue began.
Follow [this guide](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/35), but instead of `main` select `v0.4.3`.

Don't run this version for too long, since it'll spam HASS logs with `Detected blocking call to import_module`, but long enough to check whether entities update correctly.

**Comment by KaRLiKCZ** [comment]
I can't select another version than 0.4.6, even main. When I select 0.4.3 then it is automatically select to 0.4.6.

I tried call service (like is written in HA in HACS), but plum_ecomax doesn't have service for install_update...

EDIT: Unfortunatelly it is problem of HA, even it still show 0.4.6, but it install 0.4.3 :D

Will check if values get updated...

**Comment by KaRLiKCZ** [comment]
No change. No update.
![chrome_wnDQPXJXkT](https://github.com/user-attachments/assets/24a7a81d-8d9a-4e3d-ab11-29f3085012b0)

**Comment by denpamusic** [comment]
Doest it stays available now?

**Comment by KaRLiKCZ** [comment]
1 hour no change, I see (I already arrived home :) on thermostat at least different value for hot water.

**Comment by denpamusic** [comment]
Ok, then, I'll need a bit more time to figure out what might've gone wrong. There will be a lot of guesswork involved in trying to figure out what might've broken serial communication 2 months ago, especially since downgrading didn't help.

**Comment by denpamusic** [comment]
Just in case, there's no errors in the log right?

**Comment by KaRLiKCZ** [comment]
2024-07-31 18:54:36.996 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 229, in frame_consumer
    device.handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/ecomax.py", line 139, in handle_frame
    super().handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/__init__.py", line 132, in handle_frame
    if frame.data is not None:
       ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/__init__.py", line 159, in data
    self.decode_message(self._message) if self._message is not None else {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/messages.py", line 42, in decode_message
    return RegulatorDataStructure(self).decode(message)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 64, in decode
    param_id: self._unpack_regulator_data(message, data_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 35, in _unpack_regulator_data
    data_type.unpack(message[self._offset :])
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 182, in unpack
    self._value = data.split(b"\0", 1)[0].decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data
2024-07-31 18:54:39.247 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 229, in frame_consumer
    device.handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/ecomax.py", line 139, in handle_frame
    super().handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/__init__.py", line 132, in handle_frame
    if frame.data is not None:
       ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/__init__.py", line 159, in data
    self.decode_message(self._message) if self._message is not None else {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/messages.py", line 42, in decode_message
    return RegulatorDataStructure(self).decode(message)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 64, in decode
    param_id: self._unpack_regulator_data(message, data_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 35, in _unpack_regulator_data
    data_type.unpack(message[self._offset :])
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 182, in unpack
    self._value = data.split(b"\0", 1)[0].decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data
2024-07-31 18:54:41.431 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 229, in frame_consumer
    device.handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/ecomax.py", line 139, in handle_frame
    super().handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/__init__.py", line 132, in handle_frame
    if frame.data is not None:
       ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/__init__.py", line 159, in data
    self.decode_message(self._message) if self._message is not None else {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/messages.py", line 42, in decode_message
    return RegulatorDataStructure(self).decode(message)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 64, in decode
    param_id: self._unpack_regulator_data(message, data_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 35, in _unpack_regulator_data
    data_type.unpack(message[self._offset :])
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 182, in unpack
    self._value = data.split(b"\0", 1)[0].decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data
2024-07-31 18:54:43.682 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('.frames.requests', 'pyplumio') inside the event loop by custom integration 'plum_ecomax' at custom_components/plum_ecomax/connection.py, line 168: await self.device.request( (offender: /usr/local/lib/python3.12/site-packages/pyplumio/helpers/factory.py, line 16: importlib.import_module("." + module_name, "pyplumio"), class_name), please create a bug report at https://github.com/denpamusic/homeassistant-plum-ecomax/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/plum_ecomax/__init__.py", line 91, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2059, in async_forward_entry_setups
    await self._async_forward_entry_setups_locked(entry, platforms)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2070, in _async_forward_entry_setups_locked
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2072, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2152, in _async_forward_entry_setup
    await entry.async_setup(self.hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 231, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 195, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 331, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    awaitable = create_eager_task(awaitable, loop=hass.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/config/custom_components/plum_ecomax/binary_sensor.py", line 276, in async_setup_entry
    if connection.has_mixers and await connection.async_setup_mixers():
  File "/config/custom_components/plum_ecomax/connection.py", line 168, in async_setup_mixers
    await self.device.request(

**Comment by KaRLiKCZ** [comment]
I tried install 0.4.2 without any change. Still the same, only one value get update.
Log above I found with 0.4.2 version.

I will try again 0.4.6 if there will be later the same

**Comment by denpamusic** [comment]
Thanks for the head up!

Now this here is interesting:
> File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 182, in unpack
self._value = data.split(b"\0", 1)[0].decode()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data

On [line 182](https://github.com/denpamusic/PyPlumIO/blob/v0.5.15/pyplumio/helpers/data_types.py#L182) of data_type.py module is a String decoder for [RegulatorData](https://pyplumio.denpa.pro/frames.html#regulatordata) message. I wonder what field it's trying to decode and failing...

I'll need to handle it more gracefully or at least make it log a field that it's having trouble with.

**Comment by KaRLiKCZ** [comment]
Could it by, that I installed AppDeamon in between? I wanted to write some python scripts, but didn't find a time for it yet :)
I think AppDaemon has Python inside...

**Comment by KaRLiKCZ** [comment]
```
2024-07-31 20:10:00.759 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('.frames.requests', 'pyplumio') in /usr/local/lib/python3.12/site-packages/pyplumio/helpers/factory.py, line 16: importlib.import_module("." + module_name, "pyplumio"), class_name inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 204, in frame_producer
    if (response := await reader.read()) is not None:
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/timeout.py", line 32, in wrapper
    return await asyncio.wait_for(func(*args, **kwargs), timeout=seconds)
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
  File "/usr/local/lib/python3.12/site-packages/pyplumio/stream.py", line 135, in read
    frame: Frame = factory(
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/factory.py", line 16, in factory
    importlib.import_module("." + module_name, "pyplumio"), class_name
```

**Comment by KaRLiKCZ** [comment]
```
2024-07-31 20:10:06.331 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 229, in frame_consumer
    device.handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/ecomax.py", line 139, in handle_frame
    super().handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/__init__.py", line 132, in handle_frame
    if frame.data is not None:
       ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/__init__.py", line 159, in data
    self.decode_message(self._message) if self._message is not None else {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/messages.py", line 42, in decode_message
    return RegulatorDataStructure(self).decode(message)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 64, in decode
    param_id: self._unpack_regulator_data(message, data_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 35, in _unpack_regulator_data
    data_type.unpack(message[self._offset :])
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 182, in unpack
    self._value = data.split(b"\0", 1)[0].decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data
```

**Comment by KaRLiKCZ** [comment]
and the last one found:

```
2024-07-31 20:10:08.556 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 229, in frame_consumer
    device.handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/ecomax.py", line 139, in handle_frame
    super().handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/__init__.py", line 132, in handle_frame
    if frame.data is not None:
       ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/__init__.py", line 159, in data
    self.decode_message(self._message) if self._message is not None else {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/messages.py", line 42, in decode_message
    return RegulatorDataStructure(self).decode(message)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 64, in decode
    param_id: self._unpack_regulator_data(message, data_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 35, in _unpack_regulator_data
    data_type.unpack(message[self._offset :])
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 182, in unpack
    self._value = data.split(b"\0", 1)[0].decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data
2024-07-31 20:10:11.081 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 229, in frame_consumer
    device.handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/ecomax.py", line 139, in handle_frame
    super().handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/__init__.py", line 132, in handle_frame
    if frame.data is not None:
       ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/__init__.py", line 159, in data
    self.decode_message(self._message) if self._message is not None else {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/messages.py", line 42, in decode_message
    return RegulatorDataStructure(self).decode(message)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 64, in decode
    param_id: self._unpack_regulator_data(message, data_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 35, in _unpack_regulator_data
    data_type.unpack(message[self._offset :])
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 182, in unpack
    self._value = data.split(b"\0", 1)[0].decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data
2024-07-31 20:10:12.327 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('.frames.requests', 'pyplumio') inside the event loop by custom integration 'plum_ecomax' at custom_components/plum_ecomax/connection.py, line 168: await self.device.request( (offender: /usr/local/lib/python3.12/site-packages/pyplumio/helpers/factory.py, line 16: importlib.import_module("." + module_name, "pyplumio"), class_name), please create a bug report at https://github.com/denpamusic/homeassistant-plum-ecomax/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 734, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/plum_ecomax/__init__.py", line 91, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2059, in async_forward_entry_setups
    await self._async_forward_entry_setups_locked(entry, platforms)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2070, in _async_forward_entry_setups_locked
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2072, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2152, in _async_forward_entry_setup
    await entry.async_setup(self.hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 586, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 231, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 195, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 331, in async_setup_entry
    return await self._async_setup_platform(async_create_setup_awaitable)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    awaitable = create_eager_task(awaitable, loop=hass.loop)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/config/custom_components/plum_ecomax/binary_sensor.py", line 276, in async_setup_entry
    if connection.has_mixers and await connection.async_setup_mixers():
  File "/config/custom_components/plum_ecomax/connection.py", line 168, in async_setup_mixers
    await self.device.request(
```

**Comment by denpamusic** [comment]
No, nothing you installed with HASS could lead to this error. It's possible, that changing some settings on the EM controller may have caused this, but it's uncertain.

For some reason your EM controller started broadcasting a string that can't be decoded as utf-8 (has some special characters probably) as part of RegulatorData message. This also explains why this issue doesn't affect other users.

It's mostly my fault that it doesn't get handled gracefully and crashes whole task. I'll wrap it in `try: ... except UnicodeDecodeError: ...` block and that should be enough for this error. I'll get to it in a about a hour, hopefully this will be enough to fix the issue with updates

**Comment by KaRLiKCZ** [comment]
Could it be because my Thermostat (Panel) has name "Obyvak :-)", but I did that from begining.

**Comment by denpamusic** [comment]
Regulator data issue should now be fixed by relaxing error handling when decoding strings. If it encounters something undecodable in utf-8, it just replaces it with a **replacement character** (�). You can check if it fixed the whole updating issue, by installing `main` as described [here](https://github.com/denpamusic/homeassistant-plum-ecomax/issues/35).

>Could it be because my Thermostat (Panel) has name "Obyvak :-)", but I did that from begining.

I don't really know, since my EM is much simpler device and doesn't return any strings. You can however check which field caused a problem by opening diagnostics data after installing fixed version and looking for � character. Nice name btw :-)

**Comment by KaRLiKCZ** [comment]
I'm not sure which version is installed. When I open PlumECOmax in HACS then whatever I select in dropdown menu ( I selected main ) then dropdown show 0.4.6.
It does the same with 0.4.3 version. But when I download it, reset HA then I see in HACS that I have version 0.4.3.
But doing it with "main" still shows 0.4.6.

In the log there is still 
```
2024-08-01 11:45:03.847 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 217, in frame_consumer
    device.handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/ecomax.py", line 132, in handle_frame
    super().handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/__init__.py", line 139, in handle_frame
    if frame.data is not None:
       ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/__init__.py", line 161, in data
    self.decode_message(self._message) if self._message is not None else {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/messages.py", line 43, in decode_message
    return RegulatorDataStructure(self).decode(message)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 63, in decode
    param_id: self._unpack_regulator_data(message, data_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 35, in _unpack_regulator_data
    data_type.unpack(message[self._offset :])
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 183, in unpack
    self._value = data.split(b"\0", 1)[0].decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data
2024-08-01 11:45:05.751 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pyplumio/protocol.py", line 217, in frame_consumer
    device.handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/ecomax.py", line 132, in handle_frame
    super().handle_frame(frame)
  File "/usr/local/lib/python3.12/site-packages/pyplumio/devices/__init__.py", line 139, in handle_frame
    if frame.data is not None:
       ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/__init__.py", line 161, in data
    self.decode_message(self._message) if self._message is not None else {}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/frames/messages.py", line 43, in decode_message
    return RegulatorDataStructure(self).decode(message)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 63, in decode
    param_id: self._unpack_regulator_data(message, data_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyplumio/structures/regulator_data.py", line 35, in _unpack_regulator_data
    data_type.unpack(message[self._offset :])
  File "/usr/local/lib/python3.12/site-packages/pyplumio/helpers/data_types.py", line 183, in unpack
    self._value = data.split(b"\0", 1)[0].decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd8 in position 20: unexpected end of data
```

**Comment by denpamusic** [comment]
> self._value = data.split(b"\0", 1)[0].decode()

Logs show that you're still using 0.4.6, as this line is [different](https://github.com/denpamusic/PyPlumIO/blob/f135302a8255186a70a523e91e8980c888fe8e9c/pyplumio/helpers/data_types.py#L184) in main. I'll do a 0.4.7 release just with this change once I get home, then hopefully you'll be able to install it.

**Comment by KaRLiKCZ** [comment]
Installing :)

**Comment by denpamusic** [comment]
Fingers crossed🤞
There is the possibility, that this regdata error is separated one and is not what's causing the issue with updating, but hopefully this fixes updating as well.

**Comment by KaRLiKCZ** [comment]
Hot water is getting updated values, the rest is the same, but probably temperatures are stable. Will confirm tomorrow status.

**Comment by KaRLiKCZ** [comment]
Hot water and Outside temperature is updating.
Boiler and Mixer have the same temp, but it could be, that this temp is stable till now, as it is in basement.
When I reload it, than everything gets values. In past there was red exclamation.

I keep closing this bug on you.

Thanks for your time and support

**Comment by denpamusic** [comment]
Thanks for the heads up and for your great help in debugging this issue (sorry for all the troubles)!
Glad that everything seems to be working now.

I'll keep this issue open for a couple of days just in case.

**Comment by denpamusic** [comment]
If possible, could you please attach diagnostics data from the new version as well, so I can check what it was having trouble decoding before.

**Comment by KaRLiKCZ** [comment]
All values are now updating there stats. Of course not fuel, fans and pumps, but temperatures are changing :)

here is newest diagnostic

Thanks
Ondrej

[config_entry-plum_ecomax-01J47SBBGRHJPBD7CVXJN7PD71.json](https://github.com/user-attachments/files/16478973/config_entry-plum_ecomax-01J47SBBGRHJPBD7CVXJN7PD71.json)

**Comment by denpamusic** [comment]
Thanks! It seems that field with id 133 was giving us trouble with decoding, I believe it was wifi settings, so you might've changed those couple months ago, which broke the integration. Anyways it won't happen again. I also removed diagnostics file, due to sensitive information.

Glad to hear everything working now. Thanks again for your help and translation PR!
